# Generated by Django 3.0.1 on 2020-01-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('name', models.CharField(max_length=100)),
                ('intro', models.TextField()),
                ('desc1', models.TextField()),
                ('desc2', models.TextField()),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
    ]
