# Generated by Django 3.0.1 on 2020-01-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
